version: '3.8'

services:
  db_auth:
    container_name: db_auth
    build: .
    ports:
      - ${db_port_auth}:${db_port_auth}
    environment:
      - POSTGRES_USER=${db_user_auth}
      - POSTGRES_PASSWORD=${db_password_auth}
      - POSTGRES_DB=${db_name_auth}
    image: postgres:15.3-alpine
    command:
      - 'postgres'
      - '-c'
      - 'port=${db_port_auth}'
    volumes:
      - db_auth_vol:/var/lib/postgres/data
    networks:
      - server_net
volumes:
  db_auth_vol: {}
networks:
  server_net:
    driver: bridge
